### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by nestorgf2014** [mschoch/go-si4703#1]
I want to use [Sourcegraph code search and code review](https://sourcegraph.com) with go-si4703. A project maintainer needs to enable it to set up a webhook so the code is up-to-date there.

Could you please enable go-si4703 on @Sourcegraph by going to https://sourcegraph.com/github.com/mschoch/go-si4703 and clicking on Settings? (It should only take 15 seconds.)

Thank you!

**Comment by mschoch** [comment]
I have enabled it, for now.
